/**:
  ros__parameters:
    debug: true
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_x: 0.05
      sigma2_q_y: 0.05
      sigma2_q_z: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_x: 4e-4
      r_y:  5e-4 #5e-4
      r_z:  9e-4 #9e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0
    
    solver:
      prediction_delay: 0.0
      controller_delay: 0.005
      max_tracking_v_yaw: 30.0 #转速(rad/s)大于这个值时瞄准机器人中心 
      side_angle: 20.0 
      bullet_speed: 26.7
      compenstator_type: "ideal"
      gravity: 9.788
      resistance: 0.092
      iteration_times: 20 # 补偿的迭代次数
      pitch_is_reverse: -1 #pitch轴是否反向 1:正向 -1:反向
      shooting_range_width: 0.135
      shooting_range_height: 0.135
