/**:
  ros__parameters:
    target_frame: odom
    debug: true
    
    ekf:
      sigma2_q_xyz: 1e-3
      sigma2_q_theta: 2.09 # a_max * w_max
      sigma2_q_r: 0.0

      r_blade: 6e-4
      r_center: 2e-4

    gns:
      min_a: 0.4
      max_a: 1.3
      min_w: 1.5
      max_w: 2.3
      max_iter: 50
      min_step: 1e-10
      obs_max_size: 150
      a_start: 0.9125
      w_start: 1.942
      c_start: 0.0
      min_first_solve_time: 2.0

    ekf_gns:
      sigma2_q_a: 1e-5
      sigma2_q_w: 1e-5
      sigma2_q_c: 1e2
      r_a: 1e-8
      r_w: 1e-8
      r_c: 1e-8

    tracker:
      lost_time_threshold: 2.0
      max_match_theta: 0.4
      max_match_center_xoy: 1.0

      tracking_threshold: 20

      blade_z_ground: 1603.0
      robot_z_ground: 416.0
      distance: 6626.0
      max_distance_diff: 120.0
      
    solver:
      prediction_delay: 0.02
      bullet_speed: 27.0
      gravity: 9.788
      iteration_times: 30
      compensator_type: 'ideal'
      resistance: 0.092
      controller_delay: 0.005
